fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict

-   repo: local
    hooks:

    - id: remove-extra-blank-lines
      name: Remove extra blank lines
      entry: hooks/remove-extra-blank.py
      language: python
      always_run: true
      verbose: true
      files: ^src\/.+\.lagda\.md$
      types_or: [markdown, text]
      args: []
      require_serial: false

    - id: fix-imports
      name: Format Agda imports
      entry: hooks/fix-imports.py
      language: python
      always_run: true
      verbose: true
      files: ^src\/.+\.lagda\.md$
      types_or: [markdown, text]
      args: []
      require_serial: false

    - id: generate-namespace-index-modules
      name: Generate Agda namespace index modules
      entry: hooks/generate_namespace_index_modules.py
      language: python
      always_run: true
      verbose: true
      types_or: [markdown, text]
      args: []
      require_serial: false

    - id: generate-main-index-file
      name: Generate main index file
      entry: hooks/generate_main_index_file.py
      language: python
      always_run: true
      verbose: true
      types_or: [markdown, text]
      args: []
      require_serial: false


# - repo: https://github.com/pre-commit/mirrors-prettier
#   rev: "v3.0.0-alpha.6"
#   hooks:
#     - id: prettier
#       types_or: [css, javascript, markdown,yaml]
