name: Profile typechecking library
on:
  # To run this workflow manually
  workflow_dispatch:
    inputs:
      ref:
        description: the repository ref to build
        required: true
        default: master

  push:
    branches:
      - master

# Don't cancel previous runs of the same branch
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: false

jobs:
  typecheck-performance:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        agda: ['2.6.4']
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3
        with:
          path: master

      - name: Setup Agda
        uses: wenkokke/setup-agda@v2.1.0
        with:
          agda-version: ${{ matrix.agda }}

      - name: Typecheck library with profiling
        run: |
          cd master
          make check-profile
