name: Profile library typechecking
on:
  push:
    branches:
      - master

# Don't cancel previous runs of the same branch
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: false

jobs:
  typecheck-performance:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        agda: ['2.6.4']
    permissions:
      pages: write # to deploy to Pages
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3
        with:
          path: master

      - name: Setup Agda
        uses: wenkokke/setup-agda@v2.1.0
        with:
          agda-version: ${{ matrix.agda }}

      - name: Typecheck library with profiling
        run: |
          cd master
          make check-profile > temp/benchmark-results.txt 2> temp/memory-results.txt
        # Assume your make check-profile outputs a file `benchmark-results.txt`
        # in a format compatible with github-action-benchmark or converted accordingly

      - name: Parse typechecking profile
        run: |
          python3 scripts/typechecking_profile_parser.py temp/benchmark-results.txt temp/memory-results.txt temp/benchmark-results.json YOUR_CSV_HERE.csv '${{ github.sha }}'

      - name: Benchmark
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'customSmallerIsBetter'
          output-file-path: './master/temp/benchmark-results.json' # Adjust path to where your benchmark output is saved
          gh-pages-branch: 'gh-pages' # or any branch you prefer to store your benchmark results
          benchmark-data-dir-path: 'benchmarks' # Directory in the gh-pages branch where benchmark data will be stored
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true # Push and deploy GitHub pages branch automatically
