name: Profile library typechecking
on:
  push:
    branches:
      - master

# Don't cancel previous runs of the same branch
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: false

jobs:
  typecheck-performance:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        agda: ['2.6.4']
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3
        with:
          path: master

      - name: Setup Agda
        uses: wenkokke/setup-agda@v2.1.0
        with:
          agda-version: ${{ matrix.agda }}

      - name: Typecheck library with profiling
        run: |
          cd master
          make check-profile > temp/benchmark-results.txt 2> temp/memory-results.txt
        # Assume your make check-profile outputs a file `benchmark-results.txt`
        # in a format compatible with github-action-benchmark or converted accordingly

      - name: Download previous benchmark data
        uses: actions/cache/restore@v4
        with:
          path: './benchmark-cache'
          key: ${{ matrix.os }}-benchmark-${{ github.event.before }}

      - name: Process the new benchmark data
        run: |
          cd master
          python3 scripts/typechecking_profile_parser.py \
            temp/benchmark-results.txt temp/memory-results.txt \
            temp/benchmark-results.json benchmark-cache/data.csv \
            ${{ github.sha }}

      - name: Merge JSON benchmark data
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'customSmallerIsBetter'
          # Location of the new data
          output-file-path: './master/temp/benchmark-results.json'
          # Location of the aggregate data
          external-data-json-path: './benchmark-cache/data.json'

      - name: Save merged benchmark data
        uses: actions/cache/save@v4
        with:
          path: './benchmark-cache'
          key: ${{ matrix.os }}-benchmark-${{ github.event.after }}

      - name: Publish the CVS as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Benchmark data'
          path: './benchmark-cache/data.csv'

      - name: Prepare new revision of the benchmark website
        run: |
          cd master
          mkdir benchmark-website
          cp website/benchmarks/index.html benchmark-website/
          python3 scripts/benchmark_to_js.py \
            ../benchmark-cache/data.json benchmark-website/data.js

      - name: Deploy the new benchmark
        run: |
          npx netlify-cli deploy --dir=benchmark-website
